HUB-393 rabbit queue bundle
wakeapp/rabbit-queue-bundle pull request #1
Opened 2020-12-30 08:39 UTC by iskripka

2021-01-11 13:15 UTC, revilon1991 requested changes

2021-01-11 13:15 UTC, revilon1991 commented on README.md
> +# app/config.yml
app/config.yml => app/packages/wakeapp_rabbit_queue.yaml

2021-01-11 13:15 UTC, revilon1991 commented on README.md
> +/** @var \Wakeapp\Bundle\RabbitQueueBundle\Producer\RabbitMqProducer $producer*/
$producer*/ => $producer */

2021-01-11 13:15 UTC, revilon1991 commented on README.md
> +    /**
add break line

2021-01-11 13:15 UTC, revilon1991 commented on README.md
> +            // handle some task by specific logic
упомянуть про гидратор
$data = $this->decodeMessageBody($item);

2021-01-11 13:15 UTC, revilon1991 commented on README.md
> +            - { name: wakeapp_rabbit_queue.consumer}
- { name: wakeapp_rabbit_queue.consumer}
=>
- { name: wakeapp_rabbit_queue.consumer }

2021-01-11 13:15 UTC, revilon1991 commented on README.md
> +Чтобы запустить `consumer` необходимо выполнить команду `rabbit:consumer:run`rabbit.
`rabbit:consumer:run`rabbit.
=>
`rabbit:consumer:run` rabbit.

2021-01-11 13:15 UTC, revilon1991 commented on .gitattributes
> +.gitattributes    export-ignore
добавить примеры консумеров и Wakeapp\Bundle\RabbitQueueBundle\Enum\QueueEnum

2021-01-11 13:15 UTC, revilon1991 commented on README.md
> +class ExampleFifoDefinition implements DefinitionInterface
Добавить пример definition delay+deduplicate

2021-01-12 09:53 UTC, revilon1991 requested changes

2021-01-12 09:53 UTC, revilon1991 commented on Command/ConsumerRunCommand.php
> +            $signalInfo = json_encode($signalInfo, JSON_THROW_ON_ERROR);
add use block:
use const JSON_THROW_ON_ERROR;
use function json_encode;

2021-01-12 09:53 UTC, revilon1991 commented on Exception/RewindPartialException.php
> +                throw new RabbitQueueException(sprintf('Rewind message must be instance of %s', AMQPMessage::class));
add function sprintf to use block

2021-01-12 09:53 UTC, revilon1991 commented on Hydrator/JsonHydrator.php
> +            return json_decode($dataString, true, 512, JSON_THROW_ON_ERROR);
add function "json_decode" and constant "JSON_THROW_ON_ERROR" to use block

2021-01-12 09:53 UTC, revilon1991 commented on Hydrator/JsonHydrator.php
> +            return json_encode($data, JSON_THROW_ON_ERROR);
add function "json_encode" to use block

2021-01-12 12:43 UTC, revilon1991 requested changes

2021-01-12 12:43 UTC, revilon1991 commented on Command/ConsumerRunCommand.php
> +use const JSON_THROW_ON_ERROR;
скорей всего по psr-12 нужен break line между разными типами use

2021-01-12 12:43 UTC, revilon1991 commented on Hydrator/JsonHydrator.php
> +use const JSON_THROW_ON_ERROR;
скорей всего по psr-12 нужен break line между разными типами use

2021-01-12 12:43 UTC, revilon1991 commented on composer.json
> +        "ext-json": "*"
extension обычно в самом начале пишется. Возможно добавлял в ручную, а не через
composer require ext-json:*

2021-01-12 13:03 UTC, iskripka commented on composer.json
> +        "ext-json": "*"
Да, странно, хотя добавлял через require
Перенёс наверх

2021-01-12 13:24 UTC, revilon1991 approved these changes

2021-01-13 12:54 UTC, revilon1991 requested changes

2021-01-13 12:54 UTC, revilon1991 commented on README.md
> +    - [Подключение бандла](#шаг-2-подключение-бандла)
Добавить раздел требования в котором описать какие extansion'ы нужны для корректной работы и указать ссылки на них

2021-01-13 13:31 UTC, kryakozyablik requested changes

2021-01-13 13:31 UTC, kryakozyablik commented on Enum/QueueEnum.php
> +    public const EXAMPLE = 'example';
EXAMPLE -> EXAMPLE_DEDUPLICATE_DELAY  = 'example_deduplicate_delay';

2021-01-13 16:28 UTC, revilon1991 approved these changes

2021-01-14 09:17 UTC, kryakozyablik approved these changes

2021-01-14 09:18 UTC, merged